class GlobalLists {
  static Map<String, String> multipleChildrenWidgets = {
    'Column': 'children',
    'Row': 'children',
    'Stack': 'children',
    'CupertinoActionSheet': 'actions',
    'CupertinoPicker': 'children',
    'CupertinoSegmentedControl': 'children',
    // map, showed as CupertinoSegmentedControl<String>
    'CupertinoSlidingSegmentedControl': 'children',
    // map, showed as CupertinoSegmentedControl<String> && children are doubled
    'CupertinoTabBar': 'items',
  };

  static Map<String, List<String>> knownChildren = {
    'GestureDetector': ['RawGestureDetector', '_GestureSemantics', 'Listener'],
    'Container': ['ColoredBox', 'LimitedBox', 'ConstrainedBox', 'DecoratedBox'],
    'IconButton': [
      'Semantics',
      'InkResponse',
      '_InkResponseStateWidget',
      '_ParentInkResponseProvider',
      'Actions',
      '_ActionsMarker',
      'Focus',
      '_FocusMarker',
      'Semantics',
      'MouseRegion',
      '_RawMouseRegion',
      'Semantics',
      'GestureDetector',
      'ConstrainedBox',
      'Padding',
      'SizedBox',
      'Align',
      'Builder',
      'IconTheme',
      'RawGestureDetector',
      'Listener',
    ],
    'Icon': ['ExcludeSemantics', 'Center', 'RichText', 'Semantics', 'SizedBox'],
    'Spacer': [
      'Expanded',
      'SizedBox.shrink',
    ],
    'SingleChildScrollView': [
      'PrimaryScrollController',
      'Scrollable',
      'Scrollbar',
      '_MaterialScrollbar',
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'MouseRegion',
      '_RawMouseRegion',
      'CustomPaint',
      'RepaintBoundary',
      '_ScrollSemantics',
      '_ScrollableScope',
      'IgnorePointer',
      '_SingleChildViewport',
      'Semantics',
    ],
    'SelectableText': [
      'Semantics',
      'TextSelectionGestureDetector',
      'RawGestureDetector',
      'Listener',
      'RepaintBoundary',
      'EditableText',
      'MouseRegion',
      '_RawMouseRegion',
      'MouseRegion',
      '_RawMouseRegion',
      'Scrollable',
      'Scrollbar',
      '_MaterialScrollbar',
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      '_GestureSemantics',
      'CustomPaint',
      '_ScrollableScope',
      'IgnorePointer',
      'CompositedTransformTarget',
      '_Editable',
    ],
    'AppBar': [
      'Semantics',
      'AnnotatedRegion<SystemUiOverlayStyle>',
      'Material',
      'AnimatedPhysicalModel',
      'PhysicalModel',
      'NotificationListener<LayoutChangedNotification>',
      '_InkFeatures',
      'AnimatedDefaultTextStyle',
      'DefaultTextStyle',
      'Align',
      'SafeArea',
      'Padding',
      'MediaQuery',
      'ClipRect',
      'CustomSingleChildLayout',
      'Builder',
      'IconTheme',
      'DefaultTextStyle',
      'NavigationToolbar',
      'CustomMultiChildLayout',
    ],
    'ElevatedButton': [
      'Semantics',
      '_InputPadding',
      'ConstrainedBox',
      'Material',
      '_MaterialInterior',
      'PhysicalShape',
      '_ShapeBorderPaint',
      'CustomPaint',
      'NotificationListener<LayoutChangedNotification>',
      '_InkFeatures',
      'AnimatedDefaultTextStyle',
      'DefaultTextStyle',
      'InkWell',
      '_InkResponseStateWidget',
      '_ParentInkResponseProvider',
      'Actions',
      '_ActionsMarker',
      'Focus',
      '_FocusMarker',
      'MouseRegion',
      '_RawMouseRegion',
      'GestureDetector',
      'RawGestureDetector',
      'Builder',
      'IconTheme',
      'Padding',
      'Align',
      'Listener',
    ],
    'FlutterLogo': [
      'AnimatedContainer',
      'Container',
      'Padding',
    ],
    'Image': [
      'Stack',
      'Positioned',
      'Placeholder',
      'LimitedBox',
      'CustomPaint',
      'Padding',
      'FittedBox',
      'Text',
      'RichText',
    ],
    'Placeholder': [
      'LimitedBox',
      'CustomPaint',
    ],
    'Text': [
      'RichText',
    ],
    'ExcludeSemantics': [],
    'MergeSemantics': [],
    'Semantics': [],
    'StreamBuilder': [],
    'FutureBuilder': [],
    'AnimatedContainer': [
      'Container',
      'Align',
    ],
    'AnimatedBuilder': [],
    'AnimatedAlign': [
      'Align',
    ],
    'AnimatedCrossFade': [
      'ClipRect',
      'AnimatedSize',
      '_AnimatedSize',
      'Stack',
      'Positioned',
      'TickerMode',
      '_EffectiveTickerMode',
      'ExcludeSemantics',
      'FadeTransition',
    ],
    'AnimatedDefaultTextStyle': [
      'DefaultTextStyle',
    ],
    'AnimatedModalBarrier': [
      'ModalBarrier',
      'BlockSemantics',
      'ExcludeSemantics',
      '_ModalBarrierGestureDetector',
      'RawGestureDetector',
      '_GestureSemantics',
      'MouseRegion',
      '_RawMouseRegion',
      'ColoredBox',
    ],
    'AnimatedOpacity': [
      'FadeTransition',
    ],
    'AnimatedPhysicalModel': [
      'PhysicalModel',
    ],
    'AnimatedPositioned': [
      'Container',
      'Positioned',
    ],
    'AnimatedSize': [
      '_AnimatedSize',
    ],
    'Hero': [
      'SizedBox',
      'Offstage',
      'TickerMode',
      '_EffectiveTickerMode',
      'KeyedSubtree',
    ],
    'DefaultTextStyle': [
      'Semantics',
      'Listener',
      'ConstrainedBox',
    ],
    'RichText': [],
    'Padding': [],
    'MediaQuery': [],
    'CupertinoActionSheet': [
      'SafeArea',
      'Padding',
      'MediaQuery',
      'Semantics',
      'CupertinoUserInterfaceLevel',
      'Container',
      'Padding',
      'ConstrainedBox',
      'Column',
      'Flexible',
      'ClipRRect',
      'BackdropFilter',
      '_CupertinoDialogRenderWidget',
      'Builder',
      'Container',
      'Column',
      'Flexible',
      '_CupertinoAlertContentSection',
      'CupertinoScrollbar',
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'MouseRegion',
      '_RawMouseRegion',
      'CustomPaint',
      'RepaintBoundary',
      'SingleChildScrollView',
      'Column',
      'Padding',
      'DefaultTextStyle',
      '_CupertinoAlertActionSection',
      'CupertinoScrollbar',
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'MouseRegion',
      '_RawMouseRegion',
      'CustomPaint',
      'RepaintBoundary',
      'SingleChildScrollView',
      '_CupertinoDialogActionsRenderWidget',
      '_PressableActionButton',
      '_ActionButtonParentDataWidget',
      'MergeSemantics',
      'GestureDetector',
      'Scrollable',
      'Scrollbar',
      '_MaterialScrollbar',
      '_ScrollSemantics',
      '_ScrollableScope',
      'IgnorePointer',
      '_SingleChildViewport',
      'ColoredBox',
    ],
    'CupertinoFullscreenDialogTransition': [
      'SlideTransition',
      'FractionalTranslation',
    ],
    'CupertinoPageTransition': [
      'SlideTransition',
      'FractionalTranslation',
      'DecoratedBoxTransition',
      'DecoratedBox',
    ],
    'CupertinoActivityIndicator': [
      'SizedBox',
      'CustomPaint',
    ],
    'CupertinoAlertDialog': [
      'CupertinoUserInterfaceLevel',
      'MediaQuery',
      'LayoutBuilder',
      'AnimatedPadding',
      'Padding',
      'MediaQuery',
      'Center',
      'Padding',
      'ConstrainedBox',
      'CupertinoPopupSurface',
      'ClipRRect',
      'BackdropFilter',
      'Semantics',
      '_CupertinoDialogRenderWidget',
      'Column',
      'Container',
      'ColoredBox',
      'Flexible',
      '_CupertinoAlertContentSection',
      'CupertinoScrollbar',
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'MouseRegion',
      '_RawMouseRegion',
      'CustomPaint',
      'RepaintBoundary',
      'SingleChildScrollView',
      'Column',
      'Padding',
      'DefaultTextStyle',
      'LimitedBox',
      'Scrollable',
      'Scrollbar',
      '_MaterialScrollbar',
      '_ScrollSemantics',
      '_ScrollableScope',
      'IgnorePointer',
      '_SingleChildViewport',
      '_CupertinoAlertActionSection',
      '_CupertinoDialogActionsRenderWidget',
      '_PressableActionButton',
      '_ActionButtonParentDataWidget',
      'MergeSemantics',
      'GestureDetector',
    ],
    'CupertinoButton': [
      'GestureDetector',
      'Semantics',
      'ConstrainedBox',
      'FadeTransition',
      'DecoratedBox',
      'Padding',
      'Align',
      'DefaultTextStyle',
      'IconTheme',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
    ],
    'CupertinoContextMenu': [
      'GestureDetector',
      'TickerMode',
      '_EffectiveTickerMode',
      'Opacity',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
    ],
    'CupertinoDialogAction': [
      'GestureDetector',
      'ConstrainedBox',
      'Container',
      'Padding',
      'Align',
      'IntrinsicHeight',
      'SizedBox',
      'FittedBox',
      'ConstrainedBox',
      'Semantics',
      'DefaultTextStyle',
      'RawGestureDetector',
      'Listener',
      'LimitedBox',
    ],
    'CupertinoNavigationBar': [
      'Builder',
      'Hero',
      '_TransitionableNavigationBar',
      'ClipRect',
      'BackdropFilter',
      'DecoratedBox',
      'AnnotatedRegion<SystemUiOverlayStyle>',
      'DefaultTextStyle',
      '_PersistentNavigationBar',
      'SizedBox',
      'SafeArea',
      'Padding',
      'MediaQuery',
      'NavigationToolbar',
      'CustomMultiChildLayout',
      'Offstage',
      'TickerMode',
      '_EffectiveTickerMode',
      'KeyedSubtree',
    ],
    'CupertinoPageScaffold': [
      'DecoratedBox',
      'Stack',
      'Padding',
      'Positioned',
      'GestureDetector',
      'LimitedBox',
      'ConstrainedBox',
      'RawGestureDetector',
      'Listener',
    ],
    'CupertinoPicker': [
      'DecoratedBox',
      'DefaultTextStyle',
      'Stack',
      'Positioned',
      '_CupertinoPickerSemantics',
      'ListWheelScrollView',
      'NotificationListener<ScrollNotification>',
      '_FixedExtentScrollable',
      '_ScrollSemantics',
      '_ScrollableScope',
      'RawGestureDetector',
      '_GestureSemantics',
      'IgnorePointer',
      'ListWheelViewport',
      'IndexedSemantics',
      'Center',
      'CupertinoPickerDefaultSelectionOverlay',
      'Padding',
      'DecoratedBox',
      'LimitedBox',
      'ConstrainedBox',
      'Listener',
      'Semantics',
      'IgnorePointer',
      'ListWheelViewport',
      'IndexedSemantics',
      'Padding',
      'DecoratedBox',
      'LimitedBox',
      'ConstrainedBox',
      'Container',
    ],
    'CupertinoPopupSurface': [
      'ClipRRect',
      'BackdropFilter',
    ],
    'CupertinoScrollbar': [
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'MouseRegion',
      '_RawMouseRegion',
      'CustomPaint',
      'RepaintBoundary',
    ],
    'CupertinoSearchTextField': [
      'CupertinoTextField',
      'Semantics',
      'IgnorePointer',
      'Container',
      'TextSelectionGestureDetector',
      'RawGestureDetector',
      'Listener',
      'Align',
      'ValueListenableBuilder<TextEditingValue>',
      'Row',
      'Padding',
      'IconTheme',
      'Icon',
      'Expanded',
      'Stack',
      'Padding',
      'RepaintBoundary',
      'UnmanagedRestorationScope',
      'EditableText',
      'MouseRegion',
      '_RawMouseRegion',
      'Scrollable',
      '_ScrollableScope',
      'Listener',
      'RawGestureDetector',
      'Listener',
      'Semantics',
      'IgnorePointer',
      'CompositedTransformTarget',
      'Semantics',
      '_Editable',
      'Padding',
      'CupertinoButton',
      'Icon',
      'DecoratedBox',
      'ExcludeSemantics',
      'SizedBox',
      'Center',
      'RichText',
      'SizedBox',
      'Text',
    ],
    'CupertinoSegmentedControl<String>': [
      'Padding',
      'UnconstrainedBox',
      'ConstraintsTransformBox',
      '_SegmentedControlRenderWidget<String>',
      'GestureDetector',
      'IconTheme',
      'DefaultTextStyle',
      'Center',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'Semantics',
    ],
    'CupertinoSlider': [
      '_CupertinoSliderRenderObjectWidget',
    ],
    'CupertinoSlidingSegmentedControl<String>': [
      'UnconstrainedBox',
      'ConstraintsTransformBox',
      'Container',
      'Padding',
      'AnimatedBuilder',
      '_SegmentedControlRenderWidget<String>',
      'Semantics',
      '_Segment<String>',
      'MetaData',
      'IndexedStack',
      'AnimatedOpacity',
      'AnimatedDefaultTextStyle',
      'ScaleTransition',
      'Transform',
      '_SegmentSeparator',
      'AnimatedBuilder',
      'LimitedBox',
      'ConstrainedBox',
      'Padding',
      'DecoratedBox',
      'SizedBox',
      'Offstage',
      'Builder',
      'DefaultTextStyle',
      'FadeTransition',
    ],
    'CupertinoSwitch': [
      'Opacity',
      '_CupertinoSwitchRenderObjectWidget',
    ],
    'CupertinoTabBar': [
      'ClipRect',
      'BackdropFilter',
      'DecoratedBox',
      'SizedBox',
      'Builder',
      'IconTheme',
      'DefaultTextStyle',
      'Padding',
      'Semantics',
      'Row',
      'Builder',
      'IconTheme',
      'Builder',
      'DefaultTextStyle',
      'Expanded',
      'GestureDetector',
      'Padding',
      'Column',
      'Expanded',
      'Center',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
    ],
    'CupertinoTextField': [
      'Semantics',
      'IgnorePointer',
      'Container',
      'Padding',
      'TextSelectionGestureDetector',
      'RawGestureDetector',
      'Listener',
      'Align',
      'Padding',
      'RepaintBoundary',
      'UnmanagedRestorationScope',
      'EditableText',
      'MouseRegion',
      '_RawMouseRegion',
      'Scrollable',
      '_ScrollableScope',
      'Listener',
      'RawGestureDetector',
      'Listener',
      'Semantics',
      'IgnorePointer',
      'CompositedTransformTarget',
      'Semantics',
      '_Editable',
      'DecoratedBox',
    ],
    'CupertinoTimerPicker': [
      'LayoutBuilder',
      'MediaQuery',
      'CupertinoTheme',
      '_InheritedCupertinoTheme',
      'IconTheme',
      'Align',
      'Container',
      'DefaultTextStyle',
      'Row',
      'Expanded',
      'Stack',
      'NotificationListener<ScrollEndNotification>',
      'CupertinoPicker',
      'Expanded',
      'Stack',
      'NotificationListener<ScrollEndNotification>',
      'CupertinoPicker',
      'Align',
      'Text',
      'IgnorePointer',
      'Container',
      'Padding',
      'SizedBox',
      'Baseline',
      'ConstrainedBox',
      'CupertinoPickerDefaultSelectionOverlay',
      'DecoratedBox',
      'LimitedBox',
      'ConstrainedBox',
      'RichText',
      'Positioned','_CupertinoPickerSemantics',
      'ListWheelScrollView',
      'NotificationListener<ScrollNotification>',
      '_FixedExtentScrollable',
      '_ScrollSemantics',
      '_ScrollableScope',
      'Listener',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'Semantics',
      'IgnorePointer',
      'ListWheelViewport',
      'IndexedSemantics',
      'Semantics',
      'Center'
    ],
  };
}
