class GlobalLists {
  static List<String> multipleChildrenWidgets = [
    'Column', 'Row',
  ];

  static Map<String, List<String>> knownChildren = {
    'GestureDetector': ['RawGestureDetector', '_GestureSemantics', 'Listener'],
    'Container': ['ColoredBox', 'LimitedBox', 'ConstrainedBox', 'DecoratedBox'],
    'IconButton': [
      'Semantics',
      'InkResponse',
      '_InkResponseStateWidget',
      '_ParentInkResponseProvider',
      'Actions',
      '_ActionsMarker',
      'Focus',
      '_FocusMarker',
      'Semantics',
      'MouseRegion',
      '_RawMouseRegion',
      'Semantics',
      'GestureDetector',
      'ConstrainedBox',
      'Padding',
      'SizedBox',
      'Align',
      'Builder',
      'IconTheme',
      'RawGestureDetector',
      'Listener',
    ],
    'Icon': ['ExcludeSemantics', 'Center', 'RichText', 'Semantics', 'SizedBox'],
    'Spacer': ['Expanded', 'SizedBox.shrink',],
    'SingleChildScrollView': [
      'PrimaryScrollController',
      'Scrollable',
      'Scrollbar',
      '_MaterialScrollbar',
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      'RawGestureDetector',
      '_GestureSemantics',
      'Listener',
      'MouseRegion',
      '_RawMouseRegion',
      'CustomPaint',
      'RepaintBoundary',
      '_ScrollSemantics',
      '_ScrollableScope',
      'IgnorePointer',
      '_SingleChildViewport',
      'Semantics',
    ],
    'SelectableText': [
      'Semantics',
      'TextSelectionGestureDetector',
      'RawGestureDetector',
      'Listener',
      'RepaintBoundary',
      'EditableText',
      'MouseRegion',
      '_RawMouseRegion',
      'Listener',
      'MouseRegion',
      '_RawMouseRegion',
      'Scrollable',
      'Scrollbar',
      '_MaterialScrollbar',
      'NotificationListener<ScrollNotification>',
      'RepaintBoundary',
      '_GestureSemantics',
      'CustomPaint',
      '_ScrollableScope',
      'IgnorePointer',
      'CompositedTransformTarget',
      '_Editable',
    ],
  };
}